[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "RoiEditor"
version = "3.0.1"
description = "ROI Editor - a Python-app for managing (Fiji/cellpose) ROIs"
authors = [{ name = "Bart Vanderbeke" }]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8, <3.13"
dependencies = [
    "tifffile",
    "matplotlib",
    "scikit-image",
    "numpy",
    "opencv-python",
    "pyqtgraph",
    "PyQt6",
    "XlsxWriter",
    "lxml",
    "numba"
]

[project.scripts]
RoiEditor = "RoiEditor.__main__:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["RoiEditor", "RoiEditor.Lib"]
exclude = ["data", "TestData"]

[tool.setuptools.package-data]
"RoiEditor.Lib" = ["*.ui"]
