"""RoiEditor

Author: Bart Vanderbeke & Elisa
Copyright: © 2025
License: MIT

Parts of the code in this project have been derived from chatGPT suggestions.
When code has been explicitly derived from someone else's code,
I left the (GitHub) url of the original code next to the derived code.

"""
import zipfile
from typing import List, Optional
from typing import Final
from nptyping import NDArray, Shape, Float64
from concurrent.futures import ThreadPoolExecutor
import numpy as np

from roi import Roi
from tiny_log import log

from numba import njit


@njit(cache=True)
def _write_i16_be(out_buf, offset, value):
    u16 = np.uint16(np.int32(value))
    out_buf[offset] = np.uint8((u16 >> 8) & np.uint16(0xFF))
    out_buf[offset + 1] = np.uint8(u16 & np.uint16(0xFF))


@njit(cache=True)
def _read_i16_be(in_buf, offset):
    value = (np.int32(in_buf[offset]) << 8) | np.int32(in_buf[offset + 1])
    if value >= 32768:
        value -= 65536
    return np.int32(value)


@njit(cache=True)
def _encode_roi_payload_jit(x_abs, y_abs, top, left, bottom, right, header_size, roi_type):
    n = x_abs.shape[0]
    out = np.zeros(header_size + (4 * n), dtype=np.uint8)
    out[0] = np.uint8(73)   # I
    out[1] = np.uint8(111)  # o
    out[2] = np.uint8(117)  # u
    out[3] = np.uint8(116)  # t
    out[6] = np.uint8(roi_type)
    _write_i16_be(out, 8, top)
    _write_i16_be(out, 10, left)
    _write_i16_be(out, 12, bottom)
    _write_i16_be(out, 14, right)
    _write_i16_be(out, 16, n)
    x_offset = header_size
    y_offset = header_size + (2 * n)
    for i in range(n):
        _write_i16_be(out, x_offset + (2 * i), np.int32(x_abs[i]) - left)
        _write_i16_be(out, y_offset + (2 * i), np.int32(y_abs[i]) - top)
    return out


@njit(cache=True)
def _decode_roi_payload_jit(raw, header_size):
    top = _read_i16_be(raw, 8)
    left = _read_i16_be(raw, 10)
    bottom = _read_i16_be(raw, 12)
    right = _read_i16_be(raw, 14)
    n = _read_i16_be(raw, 16)
    if n < 0:
        n = 0
    xpoints = np.empty(n, dtype=np.int32)
    ypoints = np.empty(n, dtype=np.int32)
    sum_x = 0.0
    sum_y = 0.0
    x_offset = header_size
    y_offset = header_size + (2 * n)
    for i in range(n):
        rel_x = _read_i16_be(raw, x_offset + (2 * i))
        rel_y = _read_i16_be(raw, y_offset + (2 * i))
        abs_x = rel_x + left
        abs_y = rel_y + top
        xpoints[i] = abs_x
        ypoints[i] = abs_y
        sum_x += abs_x
        sum_y += abs_y
    if n > 0:
        center_x = sum_x / n
        center_y = sum_y / n
    else:
        center_x = 0.0
        center_y = 0.0
    return top, left, bottom, right, n, xpoints, ypoints, center_x, center_y


def _encode_roi_payload(x_abs: np.ndarray, y_abs: np.ndarray, top: int, left: int, bottom: int, right: int, header_size: int, roi_type: int) -> bytes:
    raw = _encode_roi_payload_jit(x_abs, y_abs, top, left, bottom, right, header_size, roi_type)
    return raw.tobytes()


def _decode_roi_payload(data: bytes, header_size: int):
    raw = np.frombuffer(data, dtype=np.uint8)
    top, left, bottom, right, n, xpoints, ypoints, center_x, center_y = _decode_roi_payload_jit(raw, header_size)
    return int(top), int(left), int(bottom), int(right), int(n), xpoints, ypoints, (float(center_x), float(center_y))

class TinyRoiFile:
    """
        TinyRoiFile implements a reader and writer for Fiji compatible ROI/zip files
        An ROI zip file is a zip file containing .roi files: "1 .roi file == 1 ROI"
        Only the ROI_TYPE_POLYGON, ROI_TYPE_TRACED, ROI_TYPE_FREEHAND can be read or written
        TinyRoiFile imposes a naming convention for ROIs and their file: Ldddd.roi
        d=digit, the number of digits is derived from the number of Rois in the zip file
        TinyRoiFile can read ROI zip files generated by cellpose if they belong to the types described above
        TinyRoiFile adds a tags.json file to the zip in which the state and the tags of the ROI are stored
        TinyRoiFile is a stripped version of https://pypi.org/project/roifile/  (Christoph Gohlke)
    """
    HEADER_SIZE: Final[int] = 64
    ROI_TYPE_POLYGON: Final[int] = 0
    ROI_TYPE_TRACED: Final[int] = 8
    ROI_TYPE_FREEHAND: Final[int] = 7
    SUPPORTED_ROI_TYPES: Final[set[int]] = {ROI_TYPE_POLYGON, ROI_TYPE_TRACED, ROI_TYPE_FREEHAND}

    @staticmethod
    def write_parallel(zip_path: str, roi_list: List[Optional[Roi]], num_threads: int = 4) -> None:
        def encode_roi(roi: Roi) -> tuple[str, bytes]:
            top, left, bottom, right = roi.bounds
            x_abs = np.asarray(roi._xpoints, dtype=np.int32)
            y_abs = np.asarray(roi._ypoints, dtype=np.int32)
            lx = len(x_abs)
            ly = len(y_abs)
            if lx * ly == 0 or lx != ly:
                log(f"Invalid ROI {roi.name} encountered while writing, length x = {lx}, length y = {ly}", type="error")
            payload = _encode_roi_payload(
                x_abs,
                y_abs,
                int(top),
                int(left),
                int(bottom),
                int(right),
                TinyRoiFile.HEADER_SIZE,
                TinyRoiFile.ROI_TYPE_POLYGON,
            )
            assert len(payload) > TinyRoiFile.HEADER_SIZE, "empty ROI"
            return roi.name + ".roi", payload

        roi_tasks = [roi for roi in roi_list if roi]
        num_tasks = len(roi_tasks)
        chunk_size = (num_tasks + num_threads - 1) // num_threads
        chunks = [roi_tasks[i:i + chunk_size] for i in range(0, num_tasks, chunk_size)]

        results = []

        def worker(chunk):
            return [encode_roi(roi) for roi in chunk]

        with ThreadPoolExecutor(max_workers=num_threads) as executor:
             for chunk_result in executor.map(worker, chunks):
                 results.extend(chunk_result)

        # for chunk in chunks:
        #     res = [encode_roi(roi) for roi in chunk]
        #     results.extend(res)


        # Step 1: construct zip in memory
        # ZIP_STORED = no compression, zip is only used for Fiji compatibility
        import io
        import json
        mem_zip = io.BytesIO()
        with zipfile.ZipFile(mem_zip, 'w', compression=zipfile.ZIP_STORED) as zipf:
            tag_json = {}
            for name, data in results:
                zipf.writestr(name, data)
            for roi in roi_list:
                if roi:
                    parent_name = roi.parent.name if roi.parent else "None"
                    roi_color: NDArray[Shape["1, 3"], Float64] | None = roi.color
                    if roi_color is not None:
                        roi_color_list = roi_color.tolist()
                        json_value = {"state": Roi.state_to_str(roi.state), "tags": list(roi.tags), "parent": parent_name, "color": roi_color_list}
                    else:
                        json_value = {"state": Roi.state_to_str(roi.state), "tags": list(roi.tags), "parent": parent_name}
                    tag_json[roi.name] = json_value
            json_data = json.dumps(tag_json)
            zipf.writestr("tags.json", json_data.encode("utf-8"))

        #Step 2: flush it in 1 move

        def save_zip(path, data):
            with open(path, 'wb') as f:
                f.write(data)

        # Fire & Forget: no need to wait for data to be saved
        # daemon=False --> makes sure that the thread is not stopped when the program is stopped
        import threading
        threading.Thread(target=save_zip, args=(zip_path, mem_zip.getvalue()), daemon=False).start()


    @staticmethod
    def _is_valid_roi_name(name: str):
        return (
            name.startswith("L") or name.startswith("N") and
            name[1:].isdigit()
        )

    @staticmethod
    def _all_L_or_N_names(entry_list: list[str]):
        return all(TinyRoiFile._is_valid_roi_name(n) for n in entry_list)
    
    @staticmethod
    def read(zip_path: str, label_image) -> List[Optional[Roi]]:
        import io
        with  open(zip_path, "rb") as zipf:
                zip_bytes = zipf.read()
        zip_buffer = io.BytesIO(zip_bytes)  # ← hier komt het verschil
        with zipfile.ZipFile(zip_buffer, 'r') as zipf:
            name_list= zipf.namelist()
            roi_data_dict = {
                name[:-4]: zipf.read(name) # drop '.roi'
                for name in name_list
                if name.lower().endswith('.roi')
            }
            tag_json=None
            has_json = "tags.json" in name_list
            if has_json:
                json_tags_data=zipf.read("tags.json")
                log("json detected",type="info",log_level=1000)
                import json
                tag_json = json.loads(json_tags_data.decode("utf-8"))


        names = list(roi_data_dict.keys())
        all_l_or_n =TinyRoiFile._all_L_or_N_names(names)

        if all_l_or_n:
            roi_indices = [int(n[1:]) for n in names]
            max_index = np.max(roi_indices)
            l = len(names)
            if l != max_index:
                log(f"Mismatch between #ROI-files and indices: #ROI-files: {l} <> max. index: {max_index} ",type="info",log_level=1000)
            num_to_use = max(max_index,l)+1
            roi_array=np.array([None] * (num_to_use),dtype=object) #List[Optional[Roi]] = [None] * (num_to_use)

            if has_json:
                for roi_name in names:
                    data = roi_data_dict[roi_name]
                    roi: Roi = TinyRoiFile._decode(data, roi_name)
                    idx = int(roi_name[1:]) # number
                    roi_array[idx] = roi
                    values = tag_json.get(roi_name, None)

                    roi.parent = None
                    roi.children = list()

                    if isinstance(values, list):
                        roi.state = Roi.str_to_state(values[0])
                        roi.tags = set(values[1:])
                    elif isinstance(values, dict):
                        roi.state = Roi.str_to_state(values.get("state", Roi.ROI_STATE_ACTIVE))
                        roi.tags = set(values.get("tags", []))
                        _parent = values.get("parent", None)
                        roi.parent = _parent if _parent and _parent != "None" else None
                        _color: NDArray[Shape["1, 3"], Float64] | None = values.get("color", None)
                        roi.color = np.array(_color) if _color else None
            else:
                for roi_name in names:
                    data = roi_data_dict[roi_name]
                    roi = TinyRoiFile._decode(data,roi_name)
                    idx = int(roi_name[1:])
                    roi_array[idx] = roi
        else:
            roi_dict = dict()
            for name in names:
                data = roi_data_dict[name]
                roi: Roi = TinyRoiFile._decode(data,name)
                roi.parent = None
                roi.children = list()
                (cx,cy) = roi.center
                idx = label_image[int(cy),int(cx)]
                roi_dict[idx] = roi
            kys = list(roi_dict.keys())
            max_index = np.max(kys)
            l = len(kys)
            num_to_use = max(max_index,l)+1
            max_digits = len(str(num_to_use))
            labels = [f"L{idx:0{max_digits}d}" for idx in range(num_to_use)]
            roi_array=np.array([None] * (num_to_use),dtype=object)
            for idx,roi in roi_dict.items(): 
                roi_array[idx]=roi
                roi.name=labels[idx]
            if l != max_index:
                log(f"Mismatch between #ROI-files and indices: #ROI-files: {l} <> max. index: {max_index} ",type="info",log_level=1000)
        return roi_array
    
    @staticmethod
    def _decode(data: bytes, name: str = "") -> Optional[Roi]:
        if data[0:4] != b'Iout':
            log(f"{name} is not a valid ROI file (missing 'Iout' signature)", type="error")
            return None

        roi_type: int = data[6]
        if roi_type not in TinyRoiFile.SUPPORTED_ROI_TYPES:
            log(f"File {name} contains a not supported ROI type: {roi_type}", type="error")
            return None

        if len(data) < TinyRoiFile.HEADER_SIZE:
            log(f"File {name} is too short to contain a valid ROI header", type="error")
            return None

        top, left, bottom, right, n, xpoints, ypoints, center = _decode_roi_payload(data, TinyRoiFile.HEADER_SIZE)
        if n <= 0 or len(xpoints) == 0 or len(ypoints) == 0:
            log(f"File {name} contains an empty ROI", type="error")
            xpoints = np.array([0], dtype=np.int32)
            ypoints = np.array([0], dtype=np.int32)
            center = (0.0, 0.0)
            n = 1

        return Roi(xpoints, ypoints, name=name, state=Roi.ROI_STATE_ACTIVE, center = center, bounds=(top, left, bottom, right), n=n)

